USE TripLink;
ALTER TABLE Destination NOCHECK CONSTRAINT ALL;
ALTER TABLE station_to_destination NOCHECK CONSTRAINT ALL;
ALTER TABLE Categories_of_Destination NOCHECK CONSTRAINT ALL;
ALTER TABLE Des_of_trip NOCHECK CONSTRAINT ALL;
ALTER TABLE Categories_to_trip NOCHECK CONSTRAINT ALL;
ALTER TABLE Feature_to_trip NOCHECK CONSTRAINT ALL;
ALTER TABLE bus_station NOCHECK CONSTRAINT ALL;

DELETE FROM Nature_trip;
DELETE FROM Feature_to_trip;
DELETE FROM Categories_to_trip;
DELETE FROM Des_of_trip;
DELETE FROM Trip;
DELETE FROM Users;
DELETE FROM station_to_destination;
DELETE FROM bus_station;
DELETE FROM Bus;
DELETE FROM Station;
DELETE FROM Agency;
DELETE FROM Categories_of_Destination;
DELETE FROM Destination;
DELETE FROM FeatureTypes;
DELETE FROM Categories;
DELETE FROM TypeTraveler;
DELETE FROM Difficulty_level;

ALTER TABLE Destination CHECK CONSTRAINT ALL;
ALTER TABLE station_to_destination CHECK CONSTRAINT ALL;
ALTER TABLE Categories_of_Destination CHECK CONSTRAINT ALL;
ALTER TABLE Des_of_trip CHECK CONSTRAINT ALL;
ALTER TABLE Categories_to_trip CHECK CONSTRAINT ALL;
ALTER TABLE Feature_to_trip CHECK CONSTRAINT ALL;
ALTER TABLE bus_station CHECK CONSTRAINT ALL;

PRINT 'All data cleared.';
GO
